(() => {
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let moving=!reduced.matches;
const toggle=document.createElement('button');toggle.className='motion-toggle';toggle.type='button';
function label(){toggle.textContent=moving?'Pause 3D motion':'Enable 3D motion';toggle.setAttribute('aria-pressed',String(moving));document.body.classList.toggle('motion-off',!moving)}
toggle.onclick=()=>{moving=!moving;label();if(moving)requestAnimationFrame(draw)};document.body.append(toggle);label();
reduced.addEventListener('change',e=>{moving=!e.matches;label();if(moving)requestAnimationFrame(draw)});
const nav=document.querySelector('.nav-inner'),links=nav?.querySelector('.links');if(links){links.id='main-navigation';const menu=document.createElement('button');menu.className='menu-toggle';menu.type='button';menu.textContent='Menu';menu.setAttribute('aria-controls',links.id);menu.setAttribute('aria-expanded','false');nav.insertBefore(menu,links);menu.onclick=()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))};links.addEventListener('click',()=>{links.classList.remove('open');menu.setAttribute('aria-expanded','false')})}
const portrait=document.querySelector('.hero .portrait');if(portrait){const stage=document.createElement('div');stage.className='portrait-stage';const frame=document.createElement('div');frame.className='portrait-frame';portrait.replaceWith(stage);stage.append(frame);frame.append(portrait);const caption=document.createElement('div');caption.className='portrait-caption';caption.innerHTML='AKACHI MADUAKO<span>Cybersecurity / Software</span>';frame.append(caption)}
const fine=matchMedia('(pointer:fine)');document.querySelectorAll('.card,.game-card,.portrait-frame').forEach(el=>{el.addEventListener('pointermove',e=>{if(!moving||!fine.matches)return;const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(1000px) rotateX(${-y*7}deg) rotateY(${x*10}deg) translateY(-4px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
const canvas=document.createElement('canvas');canvas.id='space';canvas.setAttribute('aria-hidden','true');document.body.prepend(canvas);const ctx=canvas.getContext('2d');if(!ctx)return;let w,h,dpr;function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);if(!moving)draw(0)}
const points=[];for(let i=0;i<12;i++)for(let j=0;j<24;j++){const a=i/12*Math.PI*2,b=j/24*Math.PI*2;points.push([(2+.66*Math.cos(a))*Math.cos(b),.66*Math.sin(a),(2+.66*Math.cos(a))*Math.sin(b)])}
function draw(t){ctx.clearRect(0,0,w,h);const angle=moving?t*.00009:0.4;const size=Math.min(w*.24,340);const projected=points.map(([x,y,z])=>{const rx=x*Math.cos(angle)-z*Math.sin(angle),rz=x*Math.sin(angle)+z*Math.cos(angle);const ry=y*.8-rz*.6,zz=y*.6+rz*.8;const p=5/(5+zz);return[w*.77+rx*size*p,h*.45+ry*size*p,zz]});ctx.lineWidth=.65;for(let i=0;i<12;i++)for(let j=0;j<24;j++){const k=i*24+j,p=projected[k];for(const n of [i*24+(j+1)%24,((i+1)%12)*24+j]){const q=projected[n];ctx.strokeStyle=`rgba(154,211,119,${.07+(p[2]+3)*.018})`;ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(q[0],q[1]);ctx.stroke()}}if(moving&&!document.hidden)requestAnimationFrame(draw)}
addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&moving)requestAnimationFrame(draw)});resize();if(moving)requestAnimationFrame(draw);
})();
